dubbo:
  application:
    name: dubbo_consumer
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.45.128:2181
#    address: zookeeper://192.168.16.111:2181
#  consumer:
#    version: 1.0.1
#  consumer:
#    filter: consumerFilter
#  protocol:
#    serialization:kryo
server:
  port: 8087

